extends:
  - airbnb-base
  - plugin:prettier/recommended

plugins:
  - import
  - prettier

env:
  node: true

rules:
  no-console: 0
  import/extensions: 0
  prettier/prettier: error

parserOptions:
  ecmaVersion: 6
  sourceType: module
